project:
  type: website
  render:
    - "*.qmd"
    - "!tmp-*.md"

website:
  title: "PSI AIMS SIG Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - why-r.qmd
      - 02R-tist.qmd
      - href: resources.qmd
        text: "R Resources"
      - rcollaborations.qmd
      - news.qmd
      - blog.qmd

format:
  html:
    theme: theme.scss
    css: styles.css
    toc: true
    page-layout: full
