project:
  type: website

website:
  title: "PSI AIMS SIG Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - why-r.qmd
      - 02R-tist.qmd
      - rcollaborations.qmd
      - news.qmd
      - text: "Meeting Minutes"
        href: minutes.qmd
      - blog.qmd

format:
  html:
    theme: theme.scss
    css: styles.css
    toc: true
    page-layout: full
