---
title: "Why R?"
---

SAS has been a long standing pharmaceutical industry standard for GXP work, so it's understandable that proposing to change to alternative software, would be met with resistance and trepidation. However, it's important to ask yourself "Why R?", why is there a shift by companies to start to use R alongside SAS (or even replacing SAS)? Some key justification are provided below, which could be used to persuade reluctant adopters that there truly is a business case for R adoption (and for open source collaboration in general).

# Why open-source software?

Open-source is a positive shift in mindset incorporating the following traits:

-   Adapt to survive
-   Use-and-improve
-   Challenge the status quo
-   Continuous feedback
-   Self-service learning
-   Collaborate

# R ecosystem synergies result in resource efficiencies and cost savings

R and python ecosystems are ideal for analytic engineering:

-   Modular, build-and-extend model
-   Fully integrated help documentation with further user-guide capabilities via quarto (markdown)
-   Standardised test frameworks
-   Continuous arrival of new methods and tools being written
-   Interoperability between R python and the wider Data Science ecosystem (multi-language code usage)
-   No purchase costs

Collaboration allows for a larger pool of available talent to achieve more together:

-   Reduces duplication of work being conducted within each company
-   Easy re-use of code
-   Engineering efficiencies (built in documentation/test frameworks/re-use of code & tools)

# Enhanced graphics & reporting capabilities

The following are just a few of the Enhanced graphics & reporting capabilities offered when using open-source software

-   Brilliant graphics and interactive graphics
-   Interactive story-telling capabilities through Shiny
-   Dynamic/automated reporting through quarto (rmarkdown)
-   Metadata efficiencies
-   Supports advanced analytics

# Larger community support

-   R community user support is larger than any purchased software company could provide
-   A wealth of information, help and advice available for free online

# Industry trend

Substantial work ongoing to support the use of R within pharma. This is highlighted by the number of cross industry working groups addressing each of the areas of previous concern

-   [pharmaverse](https://pharmaverse.org/e2eclinical/)
-   [R Submissions working group](https://rconsortium.github.io/submissions-wg/)
-   [RTRS working group](https://rconsortium.github.io/rtrs-wg/)
-   [R Validation Hub](https://www.pharmar.org/)
-   [CAMIS](https://psiaims.github.io/CAMIS/)

# Talent attraction and retention

The pharmaceutical industry has always struggled to bring in enough experienced SAS programmers and statisticians. Open source languages and tools will lead to a bigger pool of available talent to work in the pharmaceutical industry. New starters (Uni leavers) will know R and data science tools already. Talent from other academic and industry fields may want to transition into pharma increasing our talent pool.
Learning from each other enables the industry to move adapt quicker and embrace new technilogy quicker which leads to more efficiencies and cost savings

# Increased opportunities for cross-pharma standardization/Reduced burden for individual companies

Currently each company writes their own specific processes, SAS macros and tools. This time is "Non-billable time", at a cost to the company. [pharmaverse](https://pharmaverse.org/e2eclinical/) are providing open source industry wide standard macros for SDTM, ADaM, TFLs and tools. Moving to open source languages and tools would have the following benefits:

-   Reduced cost, burden and duplication of effort for individual companies - increased efficiencies
-   Package/macro support and documentation thorough and complete
-   Transferable knowledge when people move companies as staff are familiar with open source macros and do not have to re-learn individual company macros and tools 
-   Standardized SDTM, AdAM & TFLs means less project specific bespoke programming for common analyses / endpoints
-   From limited static approach per company to multiple innovative collaborative approaches 
-   Modular building of packages/macros enables quick adoption of new more efficient methods
