---
title: "Minutes 2024-03-15"
date: 2024-03-15
---

::: {.callout-tip collapse="true"}
## View Attendee List

- Martin Brown
- Michael Cartwright
- Matthew Neilson
- Camilo Rojas Cifuentes

:::

### Training Courses

Plan is to highlight our materials on R Introduction Training, Simulation in R and GitHub in the resources section of the website.
Then to add further links from Martin's list. Camilo will look to contribute any further ones from his side.

### Collaborations

Esig leaders meeting to be held on 25th March
Sent 2023 achievements/highlights to Adam
Understanding what our adoption of the PSI digital strategy looks like
Examples of collaboration to be presented and discussed.
Openstatsware to become a SIG - further discussion on collaboration to be had with them.
Their TaskView Hexwall is great although the text looks a little small.

DMCs and R
Difficulty of using R Shiny due to server requirements
Demonstrated flexdashboard capabilities to deliver html files for DMC meetings and mentioned size drawbacks
Work with Michael and DMC group to flag up possibilities with flexdashboard - put example on our website or link to them.

## Publicising

Get into habit of posting news and putting it on linkedin - reshares etc.
Get traffic going to the site. Not looking for lengthy blog posts but efficient news. Camilo to check out analytics on GitHub for website traffic.
If you have any news - either put it on the site or flag it up to me.
Plan to meet with Alexander Schact for his podcast to flag up the work of AIMS and pull multiple people to our website and resources.

## Phuse US Connect

Next time ask Mark and others about particular highlights from Phuse US Connect and other feedback.
